version: '3.1'

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: mydb
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin123
      INFLUXDB_USER: user
      INFLUXDB_USER_PASSWORD: user123
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb

  k6:
    image: grafana/k6:latest
    container_name: k6
    volumes:
      - ./Check.js:/Check.js
      - ./FunctionTest:/FunctionTest
      - ./Config:/Config
      - ./Common:/Common
      - ./data:/data/
    entrypoint: ["tail", "-f", "/dev/null"]
    depends_on:
      - influxdb

volumes:
  influxdb_data:
  grafana_data:

